### ISSUE TITLE
DNX Core 5.0 Support

### ISSUE THREAD

**Issue by Erok21** [cloudinary/CloudinaryDotNet#12] opened 2016-01-29 17:37 UTC
Is there any intent to add support for dnxcore50 for VNext applications? Perhaps in a prerelease branch? Please?

**Comment by rosenbergp** [comment] 2016-02-26 17:36
Erok21, thank you for suggesting to make CloudinaryDotNet into support for dnxcore50. I second that request:)

**Comment by larini** [comment] 2016-03-30 10:50
Hi, I also need it to work for dnxcore50 projects. Thanks.

**Comment by ciel** [comment] 2016-08-03 11:40
Would really be great to see this updated for `netstandard` and `netcoreapp` now that they're final and in RTM!

**Comment by manigandham** [comment] 2016-09-28 01:11
Is this being actively worked on?

Willing to do a PR but don't want to duplicate work.

**Comment by AlexKulbako** [comment] 2016-10-19 12:50
When will be support for asp.net core 1.0? Thanks.

**Comment by nadavofi** [comment] 2016-11-16 10:34
Hi all,
I'd like to let you know that we're currently testing a solution for this case, to make sure it's fully backward compatible and plan to release it by the end of the year at the latest.
We appreciate your understanding.

**Comment by paalmoest** [comment] 2017-01-18 08:13
Any progress on this ?

**Comment by roeeba** [comment] 2017-01-22 09:45
Hi @paalmoest, we aim to have this available in the next few months. Stay tuned :)

**Comment by veteze** [comment] 2017-03-10 06:52
need this stat

**Comment by MaorGariv** [comment] 2017-03-12 11:05
Hi @veteze, 
We're currently working on it. While we don't have an ETA to share, we'll update here once it's ready and published.

Thanks in advance for your patience:)

**Comment by manigandham** [comment] 2017-04-14 17:49
@MaorGariv  @roeeba @ronen-burin @nadavofi 

Any update here? It's been another month and was originally stated as end of last year at the latest. It seems like @RTLcoil has already submitted several PRs to get this done - can you let us know what the hold up here is for customers waiting on .NET Core?

**Comment by nadavofi** [comment] 2017-04-15 16:54
@manigandham, sorry for the delay. These PRs are currently in review by our R&D team and should be merged to the master branch in a couple of weeks.

We appreciate your understanding.

**Comment by ciel** [comment] 2017-04-22 13:11
Very excited to see .NET Core support!

**Comment by brightertools** [comment] 2017-05-15 12:49
How is this coming along, any ETA?

**Comment by ronen-burin** [comment] 2017-05-16 06:33
The code is merged to master and Nuget package will be published probably next week.

**Comment by mredman** [comment] 2017-05-27 08:27
I have tried cloning, compiling and referencing the library in a new .core web application (Visual Studio 2017).

This code won't compile as it requires a reference to mscorlib, which I can't seem to reference in .net Core.

```
var cloudinary = new Cloudinary();
...
var signature = cloudinary.Api.SignParameters(parameters);
```

Error:
The type 'IDictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

**Comment by mredman** [comment] 2017-06-01 06:45
Has anyone else tried using the update in .net core?

**Comment by RTLcoil** [comment] 2017-06-01 18:15
Hey @mredman,

We weren't able to reproduce it in 2015, so we installed 2017 version - and was still fine.

Try opening cloudinary in 2017 version and rebuild it, then add reference to Coudinary.NetCoreShared.dll in the web project.

Also note that CloudinaryDotNet.dll is .net classic version, while Coudinary.NetCoreShared.dll is a .net core version. Make sure you are adding the right dll reference to the .net core - Coudinary.NetCoreShared.dll

If by update you mean a general update for net core, then yes, we've added web project reference in .net core to cloudinary.net core dll (Coudinary.NetCoreShared.dll) and are using directive
 
using CloudinaryDotNet;
 
Which makes it possible to use cloudinary object with all properties and methods.
 
var cloudinary = new Cloudinary();
 
If you're still having same issues as you described, try building cloudinary before and then restore nuget packages.

Let me know if that helps,
Oleg

**Comment by mredman** [comment] 2017-06-02 08:33
Hi,

ok thanks for the reply, I compiled this with VS2015 as thats what it opened in after cloning, will do the same test with VS2017.

Will keep your posted..

Mark

**Comment by mredman** [comment] 2017-06-02 08:58
Should I have cloned the master branch? or is there a specific branch for .net core?

**Comment by RTLcoil** [comment] 2017-06-02 16:11
There's no specific branch for .net core, it all goes directly to master.

**Comment by mredman** [comment] 2017-06-04 10:24
I was referencing Cloundinary.dll not the Coudinary.NetCoreShared.dll  :-/

To run my app I have to add this shared project to the solution and reference the project otherwise my app could not find the dll, this if fine for now to get up to speed with everything until the nugget packages are available.

@RTLcoil , thanks for your help.

**Comment by RTLcoil** [comment] 2017-06-04 10:56
Perfect, happy it helped!

**Comment by mredman** [comment] 2017-06-18 12:17
Just wondering if the nuget packages going to be updated soon?

**Comment by mredman** [comment] 2017-07-08 05:57
Referencing the shared project, there seems to be some incompatible packages with netcoreapp1.1 which causes errors and projects cannot be published with these errors, specifically relating to:
Microsoft.AspNet.Http.Abstractions
Microsoft.Extensions.WebEncoders.Core

When can we see an update that can be referenced via nuget for .net core, Is there any definitive ETA on this?

We would love to use your product, and this is holding us back.

**Comment by mredman** [comment] 2017-07-11 08:58
Will try out imgix on .Net Core, anyone had success with this or other solutions that support .net core?

**Comment by roeeba** [comment] 2017-08-27 12:53
Hi all, we're currently facing some issues with the release of the .Net Core support. The team is working hard to fix these as soon as possible. We will update here as soon as it's ready. While we cannot guarantee a specific ETA, we hope to get this resolved in the next couple of weeks.

**Comment by HarelM** [comment] 2017-08-27 13:15
I suggest to migrate to visual studio 2017 if you haven't done so already, it greatly simplifies .net core stuff...

**Comment by mredman** [comment] 2017-09-10 13:20
How is this closed!?

**Comment by roeeba** [comment] 2017-09-11 08:27
Hi, @mredman. This issue is still open. I just added a reference to a closed thread. I guess it confused you :)

**Comment by mredman** [comment] 2017-09-11 08:49
Yes, I just saw "Closed" thanks,

I hope we can use your service in .net core soon.

**Comment by mredman** [comment] 2017-09-19 06:46
Guys, it really has been months & months of waiting for this, any news?

**Comment by mredman** [comment] 2017-09-19 06:53
I have tried cloning and compiling in VS2015 and VS2017 and referencing the project in a .net Core 2.0 application, its seems to compile with a few warnings but won't publish due to some errors, so it cannot be used as it stands.

Has anyone got any tips on getting this to a working state so we can start using this library in .net core? The Cloudinary product looks great, but we really need some level of support to make a decision to wait for this or move on.

**Comment by brightertools** [comment] 2017-10-01 11:13
Any indication of an ETA?

**Comment by roeeba** [comment] 2017-10-04 11:04
Hey, guys. 
We've just published a Release Candidate of the CloudinaryDotNet SDK. This release introduces support for .Net Standard and Core.
A final release will be published in the next few weeks (depending on the feedback we'll receive).
We'd appreciate any feedback you guys will have.

**Comment by mredman** [comment] 2017-10-04 11:19
@roeeba Thanks, will have a look, do we need to get the 'review' branch?

**Comment by mredman** [comment] 2017-10-04 11:21
ok, I can see 1.1.0-rc1 via nuget.

**Comment by roeeba** [comment] 2017-10-04 11:23
@mredman Yes :) just updated my comment.

**Comment by midnight-lizard-extension** [comment] 2018-08-27 08:02
Does this mean that you support dotnet core now?
Shouldn't it be mentioned in the docs?
From docs:
![image](https://user-images.githubusercontent.com/39124616/44648055-8abdc700-a9e8-11e8-8a27-3175e592ed07.png)

**Comment by roeeba** [comment] 2018-08-27 16:14
Hi @midnight-lizard-extension. We indeed support .Net Core. Thanks for your feedback! We'll review our documentation and will make to update it accordingly.

**Closed by roeeba** 2018-08-27 16:14 UTC
Labels: enhancement
