### ISSUE TITLE
Cant save on ASP.NET site

### ISSUE THREAD

**Issue by dsvictorh** [cloudinary/CloudinaryDotNet#20] opened 2016-11-22 23:04 UTC
I am having an issue saving an image from my back-end. I get the error "File is Empty" like if I had sent nothing at all. I get a file from a controller action, check that it indeed has the necessary data and send its stream as your FileDescription class can be instantiated by passing a file name and a stream but it does not work.

Code that calls the service (File is of type HttpPostedFileBase):
`var result = CloudinaryService.UploadImage("pages/" + _page.UploadFolder, fileName, File.InputStream);`

Service: 
```
 public static UploadResult UploadImage(string folderStructure, string fileName, Stream stream)
        {
            var uploadParams = new ImageUploadParams()
            {
                File = new FileDescription(fileName, stream),
                Folder = folderStructure,
            };

            var result = new Cloudinary(GetAccount()).Upload(uploadParams);
            return new UploadResult {
                uri = result.SecureUri,
                error = result.Error != null ? result.Error.Message : string.Empty
            };
        }
```

**Comment by RTLcoil** [comment] 2016-11-27 17:06
Hi Victor!
Thanks for your request. We have tried to reproduce the issue with the code similar to yours, but everything works fine. Maybe our environment differs from yours. Could you please send us some sample project where we can see this issue?

**Comment by dsvictorh** [comment] 2016-11-27 17:18
My approach had the stream come from an HttpPostedFiledBase param's InputStream property on a .NET MVC JsonResult type controller action. I made sure the InputStream property had all the file data accordingly and up to the point where used in the FileDescription constructor.

I was unable to make it work, however, I changed it some time ago now. I proceeded to temporarily store the file instead and use the server path to instantiate the FileDescription rather than using a stream. I still need to test this on production but as far as I'm concerned it has solved my issue from the Cloudinary side.

**Comment by RTLcoil** [comment] 2016-11-27 18:44
Thanks for the update. We would still like to look into it thought because even though you solved this, the same problem might be reproduced by other developers and we want to prevent that. Any chance you can share with that the project where we can see this happening? It would just save us time rather than creating a test project ourselves.

**Comment by dsvictorh** [comment] 2016-11-27 18:49
Unfortunately I am not at liberty to disclose the project under direct orders. I apologize for the inconvenience

**Comment by MaorGariv** [comment] 2017-10-03 08:36
Hi, 

Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Closed by MaorGariv** 2017-10-03 08:36 UTC
